[[d1_databases]]
binding = "DB"
database_name = "catalogo_db"
database_id = "4966ff26-ed00-432d-a6ac-7232a6bf7d05"

[[r2_buckets]]
binding = "FOTOS"
bucket_name = "pedribel-motos"
preview_bucket = false
